### PR TITLE
Don't try to replace minVersion, maxVersion in release.sh

### PR DESCRIPTION
**Pull request by zuphilip**
There are now two minVersion and maxVersion in the
install.rdf and therefore the simple perl expressions
to replace them if needed, does not work anymore.

However, it seems no problem to do this manually
before starting the release script and therefore
I just added a prompt in the script.

### CODE REVIEW

**Comment by dstillman** [comment]
I think we can just out the prompt and leave hard-coded min/max versions in install.rdf from now on. I'm not sure if current Zotero even checks version compatibility, and this won't be relevant in the future anyway.

**Comment by zuphilip** [comment]
Do you mean to "leave out the prompt", i.e. delete it?

**Comment by dstillman** [comment]
Yes, sorry.

**Comment by zuphilip** [comment]
Okay, done. Please have a look at the new version.

**Comment by dstillman** [comment]
Looks good.

**Pull request merged**
