### PR TITLE
set editor firstLineNumber to 15, so that .ci/checkTranslator's resul…

### PR DESCRIPTION
**Pull request by mtrojan-ub**
…t matches line number in Scaffold

special wish from @ruschein

### CODE REVIEW

**Comment by adam3smith** [comment]
I seem to have a recollection this has come up before -- I don't think the line 15 is actually exact since the meta head can vary in length and so this wasn't accepted last time (because a "kind of right" is arguably more confusing than a "obviously wrong", but I might be misremembering.

**Comment by zuphilip** [comment]
We only started to discuss this in #48.

Did you test this changes? There are different places where a line number is reported (testing within scaffold, CI outside, during translation in browser) and I think the offset is not always the same.

**Comment by zuphilip** [comment]
E.g. within Scaffold on an error `2` is subtracted: https://github.com/zotero/scaffold/blob/79dd06a09106ec0c35798e62596778948ab909c3/src/chrome/content/scaffold/scaffold.js#L506

**Comment by dstillman** [comment]
Superseded by #91

**Pull request closed without merging**
