### PR TITLE
Move browser tab

### PR DESCRIPTION
**Pull request by zuphilip**
This solves #53.

Here is a preview:

scaffold-move-browser

Now, we might want to delete one of the `Current URL`. I suggests to have that in the browser pane only. Should we also delete the `Test Frame`?

### CODE REVIEW

**Comment by adomasven** [comment]
> Now, we might want to delete one of the Current URL. I suggests to have that in the browser pane only.

Agreed.

> Should we also delete the Test Frame?

The connectors have capacity to run translators in frames, so probably not.

**Comment by dstillman** [comment]
Can you rebase this on top of master and resolve conflicts?

**Comment by adam3smith** [comment]
@dstillman once this is accepted, would you mind putting out a release? Having to build Scaffold from git (while trivially easy) is yet another thing we have to walk first-time contributors through and it'd be nice to be able to just point them at the .xpi again.

**Comment by zuphilip** [comment]
See #55 for new version based on master (that was easier than rebasing and solving conflicts with spaces...)

**Comment by adomasven** [comment]
Closed with #55

**Pull request closed without merging**
